version: "3.1"
services:
   pal:
      image: dtr.dte.com/udit.panchal/pam:1.0.0
      #command:  
      #volumes:
         #- /DHDP_DTRDEV/moh_data/opal_shared_config/dev_mimms/server.xml:/opt/ibm/wlp/usr/servers/defaultServer/server.xml
      networks:
         - dev_mimms_pal_hrm_network_v31
      #secrets:
         #- keystore.jks
         #- truststore.jks
         #- app_enc_key.xml
      ports:
         - "8005"
         - "8080"
      deploy:
         placement:
            constraints:
               - node.role == worker
               - node.labels.mohltc.env.name == dev
               #- node.hostname == ontpand0bav668.dte.com 
         mode: replicated
         replicas: 1 
         #resources:
            #limits:
               #cpus: '0.5'
               #memory: 2048m
         restart_policy:
            condition: on-failure
            max_attempts: 3
            window: 60s
         labels:
            com.docker.lb.hosts: devv31.mimms.pal.dte.com
            com.docker.lb.network: dev_mimms_pal_hrm_network_v31
            com.docker.lb.port: 8080
networks:
  dev_mimms_pal_hrm_network_v31:
    external:
      name: dev_mimms_pal_hrm_network_v31 
#secrets:
   #keystore.jks:
      #external: true
   #truststore.jks:
      #external: true
   #app_enc_key.xml:
      #external: true
